### PR TITLE
fix outcome on http 200 responses

### LINKED ISSUE #30: Form POST: HTTP 200 response with empty body is a failure
When the Outcome on match and search term are unspecified, the default "success" outcome should be returned.

### PR DESCRIPTION
**Pull request by jgrayson676**
fixes #30

### CODE REVIEW

File: src/response.coffee [hunk 1]
```diff
@@ -68,6 +68,8 @@ response = (vars, req, res) ->
     else
       inverseOutcome(searchOutcome)
 
+  if !vars.outcome_search_term and !vars.outcome_on_match and res.status is 200
+    outcome = 'success'
```
Comment (cgrayson) [inline src/response.coffee]: With all the tons of other stuff going on in this function, I wonder if this special case could be moved up to the top, instead of tucked in here. Similar to the `if errorStatus()` line, where it short-circuits early and skips the rest of this, is what I'm thinking. The way it is now, the logic looks like there could still be a `reason` set after this `outcome` of "success" (even if that's supposed to be impossible) 😉

Comment (jgrayson676) [inline src/response.coffee]: So setting the `event` object with appended fields ([this block](https://github.com/activeprospect/leadconduit-integration-custom/blob/bb815ccbfdcef9867801aa828a2f2a97a9e25c02/src/response.coffee#L120-L130)) should happen earlier in the function?

Comment (cgrayson) [inline src/response.coffee]: Oh, my bad, I missed that. It still seems weird and complicated that `outcome` is set on lines 65-69, and then possibly reset after. This new case and that other searching is mutually exclusive, right? Maybe this new `if` and `outcome` assignment could be done earlier (around line 16), and the `else` would have most of [this block](https://github.com/activeprospect/leadconduit-integration-custom/blob/bb815ccbfdcef9867801aa828a2f2a97a9e25c02/src/response.coffee#L17-L69) (except setting `reasonSelector`, I think). 

If some or all of that block were factored out into a function (or more than one, maybe?), that might help clarify what's going on, too. Up to you.

File: src/response.coffee [hunk 2]
```diff
@@ -22,52 +22,56 @@ response = (vars, req, res) ->
...
-
-      else if _.isString(doc)
-        # this is plain text
-        doc
-
-    else
-      # no search path was provided, so search the entire response body
-      res.body
+  # default to success if no search term and no outcome are specified
+  if !vars.outcome_search_term and !vars.outcome_on_match
```
Comment (jgrayson676) [inline src/response.coffee]: I removed the check for `res.status` of 200 (which probably should have checked for 2xx?) which was initially included because I misread the issue.

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,10 @@
 All notable changes to this project will be documented in this file.
 This project adheres to [Semantic Versioning](http://semver.org/).
 
+## [2.7.1] - 2016-06-09
+### Fixed
+- HTTP 200 responses are now treated as success if no outcome on match and no search term are specified
```
Comment (cgrayson) [inline CHANGELOG.md]: This should be reworded a bit now, right?

**Comment by cgrayson** [comment]
Otherwise LGTM 👍
